name: Update README

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/5 * * * *'
    #- cron: '0 0 */1 * *'
permissions:
  contents: write

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948 # v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
          
      - name: Inject waka markers into README
        run: |
          sed -i 's/📊 \*\*\&nbsp;this week i spent my time on:\*\*/📊 **\&nbsp;this week i spent my time on:**\n\n<!--START_SECTION:waka-->\n<!--END_SECTION:waka-->/' README.md
          sed -i 's/📺\&nbsp;Latest YouTube Videos/📺\&nbsp;Latest YouTube Videos\n\n<!-- YOUTUBE:START -->\n<!-- YOUTUBE:END -->/' README.md
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
        with:
          commit_message: 'Update generated README'
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
