name: Waka - Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 am UTC
    # - cron: "0 0 * * *"
    
    # Runs every 30 minutes
    - cron: '*/5 * * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494 # v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
